version: '3.8'

services:
  wordpress:
    build: .
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wp}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX:-wp_}
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD','direct');
        @ini_set( 'upload_max_filesize' , '80M' );
        @ini_set( 'post_max_size', '80M');
    volumes:
      - wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wp}
      - MYSQL_USER=${MYSQL_USER:-wp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wp}
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wp-content:
  mariadb-data:
