version: '3.8'

services:
  wordpress:
    image: wordpress:5.8.0-php7.4-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wp}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wp}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX:-wp_}
    volumes:
      - wp-content:/var/www/html/wp-content
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wp}
      - MYSQL_USER=${MYSQL_USER:-wp}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wp}
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  wp-content:
  mariadb-data:
